# Generated by Django 4.2.4 on 2023-12-02 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_products_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='background_image',
            field=models.ImageField(default=False, upload_to='product.image/'),
        ),
    ]
