# Generated by Django 4.2.4 on 2023-12-02 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_orderitem_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='total',
        ),
    ]
