# Generated by Django 4.2.4 on 2023-12-09 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_remove_orderitem_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='display_id',
            field=models.IntegerField(null=True),
        ),
    ]
