# Generated by Django 4.2.4 on 2023-12-09 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_remove_products_display_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(max_length=25),
        ),
    ]
